### PR TITLE
Restify

### PR DESCRIPTION
**Pull request by killdash9**

### CODE REVIEW

**Comment by killdash9** [comment]
looks like it didn't pass your integration tests.  Any idea what could have broke them?

**Comment by kwhitley** [comment]
I see that, looking at the code now… I’ll track it down before long hopefully. Thanks for the PR!

~ Kevin @krwhitley.com
On Tue, Jan 10, 2017 at 1:56 PM, Russell Black <notifications@github.com> wrote:
looks like it didn't pass your integration tests. Any idea what could have broke them?

**Comment by kwhitley** [comment]
@killdash9 It looks like you're only accumulating text content, but res.write and res.end can (and often do) write via Buffer... working to modify to play nicely with Buffers now.

**Comment by killdash9** [comment]
That makes sense.  I wasn't sure how to deal with buffers since I am rather new to NodeJS.  Thanks!

**Comment by kwhitley** [comment]
No worries @killdash9, thanks for your help!  I've solved the issue with Buffers, but your code allows the basic functionality of:

```js
res.write('a')
res.write('b')
res.write('c')
res.end()
```

...which was previously broken.  Additionally I've taken the opportunity to add gzip support.  Before, the compression library was mutating the headers after they'd been injected into the cache, forcing a double gzip (fail) when fetching and trying to send.

Version minor bump, and added your name to the docs - cheers!

**Comment by kwhitley** [comment]
Closing this in favor of modified local branch #59

**Pull request closed without merging**
