### PR TITLE
Prevent browser caching on requests that are configured to not get cached.

### PR DESCRIPTION
**Pull request by andredigenova**
I am having an issue with the browser caching error responses even though I have configured apicache to only cache on HTTP 200.

Right now a cache-control header to instruct the browser to cache the response is being sent even if apicache is configured to not cache the response.

### CODE REVIEW

**Comment by andredigenova** [comment]
Just to be clear since coveralls is upset -- testing was added for this.

**Comment by kwhitley** [comment]
So the problem I see with this (at a glance) is that you are reintroducing the `res.send` to the flow - and only applying your logic to it.  If you were to use `res.json` or specifically use `res.write`/`res.end`, it would all be bypassed.  Thus your logic/test coverage isn't enough (try serving a 400 with something other than `res.send` to verify).  I originally hijacked `res.send` and `res.json` but removed it all (with some headaches) to be more flexible to different content types, response generation methods, etc.

I'd recommend moving the logic into the existing `res.end` monkeypatch instead of adding `res.send`.  This is called behind the scenes for all these calls anyway (including `res.send`).

**Comment by kwhitley** [comment]
**Bonus:** If you move the logic, your test should still pass! 👍

**Comment by kwhitley** [comment]
I *think* this should also solve #75

**Comment by andredigenova** [comment]
I tried to use res.end originally, but it is too late in the the request lifecycle to tamper with headers. PR #75 tried to implement it this way and that is the reason it isn't passing Travis CI.

I believe res.json/.jsonp/etc. use res.send in their underlying implementations otherwise the cache-control header unit test against /api/movies would fail since /api/movies implements its response with res.json.

However, res.write I'm not so sure -- I'll add to the writeandend unit test to verify.

**Comment by kwhitley** [comment]
Good point regarding the lifecycle... I'm pretty sure res.send won't work for accumulated buffer writes (using write+end), but if it does, maybe we can simplify further!  I can't remember - it's been awhile since we worked all those edge cases out.

Thanks for investigating!

**Comment by andredigenova** [comment]
It turns out write+end does not use send to be implemented which makes sense since write+end is a lower level of abstraction. I added a test for the cache-control headers on the write-end tests and they did fail.

I have moved the monkey patch from res.send to res.writeHead which appears to achieve the desire result.

**Comment by kwhitley** [comment]
Thanks @andredigenova 👍 🍾

**Pull request merged**
