### PR TITLE
add text and html tests

### LINKED ISSUE #52: TODO: Test with encoding types/formats
test with non JSON/text formats

### PR DESCRIPTION
**Pull request by svozza**
Fixes #52

### CODE REVIEW

**Comment by svozza** [comment]
Interesting, the restify html tests fail. I'll investigate later.

**Comment by svozza** [comment]
Ah it's because Restify doesn't support html out of the box.

**Comment by kwhitley** [comment]
Merging pending your other changes... 👍

**Comment by kwhitley** [comment]
Yeah, tried to merge and noticed the failing html tests... we can sort this after sorting the node-restify stuff

**Pull request merged**
