### PR TITLE
Revamp redis support

### LINKED ISSUE #164: Headers cannot be overwritten when cached response is served
Headers cannot be overwritten with the global options, since `^1.4.0` and https://github.com/kwhitley/apicache/commit/beaaa70076bdaaa94008638f500f87c940197713

When the cached response is delivered, regardless of `globalOptions.headers` are overwritten with the decrementing max-age value.

1. This is not the expected behaviour as these headers are in my opinion meant to be used whatever the cached response is.

2. There is a critical bug in the computation of the value of max-age: depending on how slow the evaluation of the cached expiration is compared to actually calculating the remaining max-age, the `max-age` value can be negative (usually -1 because of the `fixed(0)`).

In our real world application it has happened several times in a matter of days, with a 60 second cache duration. We had to revert to `apicache@^1.3.1`.

FYI a `max-age=-1` header is interpreted by a CDN as an infinite cache...

### LINKED ISSUE #169: Missing redis support for groups (create/delete)
apicache only works for apps running in a single server as it uses local memory to store key names and groups. When deleting groups on an app running on multiple physical servers (load balancing) it is impossible to expire a group as the server receiving the request might or might not have the complete `index`

What would be the recommended implementation for apps like this with redis ? We could store the index as a SET in redis and do similar operation when clearing the cache. Maybe an easier way to support this use case is to allow a prefix option ?

### LINKED ISSUE #197: Header option bugs
Middleware localOptions.headers currently are ignored (only globalOptions.headers are used)
https://github.com/kwhitley/apicache/blob/f27cb2b30719e8eb35ef98c6c019dd1d5ec96732/src/apicache.js#L189-L195

Also, following code is ignoring the possibility of `cacheObject.headers['cache-control']` being a value previously overrided by global/localOptions, like e.g. `max-age=0, must-revalidate` or `no-cache` or maybe a max-age lower than that being currently set.
I mean, if there was global/localOptions.headers['cache-control'] that was used when caching response, i think it should be used when sending cached response
https://github.com/kwhitley/apicache/blob/f27cb2b30719e8eb35ef98c6c019dd1d5ec96732/src/apicache.js#L251-L259

### PR DESCRIPTION
**Pull request by arthurfranca**
As it messed with same files of my previous unreviewed PRs, it also fixes header options.
It is also an alternative to PR #201 that aims to not block other queries when serving a big response.

Fix #197, fix #164 and fix #169

### CODE REVIEW

**Comment by ccckblaze** [comment]
tested, good to go

**Comment by arthurfranca** [comment]
fix #189

**Comment by arthurfranca** [comment]
PR finished

**Comment by arthurfranca** [comment]
For those who may be looking.. The PRs weren't being reviewed so i created this [apicache-plus](https://github.com/arthurfranca/apicache-plus)

**Pull request closed without merging**
