### PR TITLE
Node support 7.7

### PR DESCRIPTION
**Pull request by kwhitley**

### CODE REVIEW

**Comment by kwhitley** [comment]
Release pending the following [node-restify](https://www.npmjs.com/package/node-restify) fix:
https://github.com/restify/node-restify/issues/1429 (issue)
https://github.com/restify/node-restify/pull/1440 (PR)

**Comment by kwhitley** [comment]
The above fix should clear tests...

**Comment by svozza** [comment]
So the Restify fix has been merged! We can either wait for v5.0.2 to drop or we can just reference the commit hash in our `package.json`.

**Comment by svozza** [comment]
So this is weird, all the tests on this branch are working even though the latest version of Restify released on NPM is `5.1.0` from 5 days ago so my fix wouldn't be present there.

**Comment by kwhitley** [comment]
@svozza I definitely don't get that (passing tests).  I implemented your fix locally to the project a week or so ago for continued local development while we wait, but as soon as I blew away my modules and reloaded (5.1.0) it failed again on the status codes.

**Comment by svozza** [comment]
Ah wait, my mistake, I hadn't deleted my `node_modules`; I had changed the Restify version in `package.json` to this beforehand:

```
...
"restify": "restify/node-restify#5abc06779df3b3ed4faf4d19f0815051a7c3106b",
...
```
The tests don't pass if I revert back `^5.0.1`.

**Pull request merged**
